# Generated by Django 2.1.15 on 2020-06-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attribution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attribution',
            new_name='Feature',
        ),
    ]
